# Generated by Django 5.1.1 on 2025-05-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='copmpleted',
            new_name='completed',
        ),
    ]
