# Generated by Django 5.1.1 on 2025-05-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=150, verbose_name='Кодовое наименование функции')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное наименование функции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание функции')),
            ],
            options={
                'verbose_name': 'Функция ПО',
                'verbose_name_plural': 'Функции ПО',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата события')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время события')),
                ('log_data', models.TextField(verbose_name='Событие')),
                ('app_name', models.CharField(max_length=150, verbose_name='Наименование приложения')),
                ('method_name', models.CharField(max_length=150, verbose_name='Наименование метода')),
                ('program_version', models.CharField(default='версия 0.1.0 "Альфа-тестирование"', max_length=150, verbose_name='Версия ПО')),
                ('program_user', models.CharField(max_length=150, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('secondname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес электронной почты')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
                ('reason_locked', models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина блокировки')),
                ('django_auth_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата предоставления права')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время предоставления права')),
                ('access', models.BooleanField(verbose_name='Разрешено')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина предоставления/отзыва права')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserLogApp.function', verbose_name='Функция ПО')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to='UserLogApp.user', verbose_name='Инициатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='UserLogApp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Право пользователя',
                'verbose_name_plural': 'Права пользователей',
            },
        ),
    ]
